-- Logistics Dashboard initial schema
-- Designed for Streamlit + supabase-py.
-- RLS is enabled before API grants.

create extension if not exists pgcrypto;

create table if not exists public.fleet_data (
    id uuid primary key default gen_random_uuid(),
    truck_id text not null unique,
    driver text not null,
    status text not null default 'Available'
        check (status in ('Available','In Transit','Loading','Unloading','Delayed','Maintenance')),
    lat double precision,
    lon double precision,
    destination text,
    cargo text,
    priority text not null default 'Normal'
        check (priority in ('Low','Normal','High','Critical')),
    eta timestamptz,
    last_update timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create table if not exists public.dispatch_log (
    id bigint generated by default as identity primary key,
    fleet_id uuid references public.fleet_data(id) on delete cascade,
    event_type text not null,
    details text,
    event_time timestamptz not null default now()
);

create table if not exists public.inventory_items (
    id uuid primary key default gen_random_uuid(),
    item_code text not null unique,
    item_name text not null,
    category text not null default 'General',
    stock_qty integer not null default 0 check (stock_qty >= 0),
    reorder_level integer not null default 0 check (reorder_level >= 0),
    location text,
    condition text default 'Serviceable',
    updated_at timestamptz not null default now()
);

create index if not exists fleet_data_status_idx on public.fleet_data(status);
create index if not exists fleet_data_last_update_idx on public.fleet_data(last_update desc);
create index if not exists dispatch_log_event_time_idx on public.dispatch_log(event_time desc);
create index if not exists inventory_items_category_idx on public.inventory_items(category);

alter table public.fleet_data enable row level security;
alter table public.dispatch_log enable row level security;
alter table public.inventory_items enable row level security;

create policy "public read fleet"
on public.fleet_data for select
to anon
using (true);

create policy "public read dispatch log"
on public.dispatch_log for select
to anon
using (true);

create policy "public read inventory"
on public.inventory_items for select
to anon
using (true);

create policy "authenticated fleet select"
on public.fleet_data for select
to authenticated
using (true);

create policy "authenticated fleet insert"
on public.fleet_data for insert
to authenticated
with check (true);

create policy "authenticated fleet update"
on public.fleet_data for update
to authenticated
using (true)
with check (true);

create policy "authenticated fleet delete"
on public.fleet_data for delete
to authenticated
using (true);

create policy "authenticated dispatch select"
on public.dispatch_log for select
to authenticated
using (true);

create policy "authenticated dispatch insert"
on public.dispatch_log for insert
to authenticated
with check (true);

create policy "authenticated inventory select"
on public.inventory_items for select
to authenticated
using (true);

create policy "authenticated inventory insert"
on public.inventory_items for insert
to authenticated
with check (true);

create policy "authenticated inventory update"
on public.inventory_items for update
to authenticated
using (true)
with check (true);

create policy "authenticated inventory delete"
on public.inventory_items for delete
to authenticated
using (true);

grant select on public.fleet_data, public.dispatch_log, public.inventory_items to anon;
grant select, insert, update, delete on public.fleet_data, public.dispatch_log, public.inventory_items to authenticated;
grant usage, select on sequence public.dispatch_log_id_seq to authenticated;
grant all on public.fleet_data, public.dispatch_log, public.inventory_items to service_role;
grant usage, select on sequence public.dispatch_log_id_seq to service_role;
